### ISSUE TITLE
Clarification on file format

### ISSUE THREAD

**Issue by rp-applied** [OpenSimulationInterface/osi-visualizer#30]
Hi there, I'm having a bit of trouble creating a file that the visualizer can read.

Does the following snippet look like the correct way to generate a valid .txt file?

thanks

```

import osi_sensorview_pb2
import osi_sensordata_pb2
import osi_common_pb2

sensor_view = osi_sensorview_pb2.SensorView()
new_cam_sensor = sensor_view.camera_sensor_view.add()
ground_truth = sensor_view.global_ground_truth
some_lane =  ground_truth.lane.add()
center_line = some_lane.classification.centerline.add()
center_line.x = 0
center_line.y = 10
center_line = some_lane.classification.centerline.add()
center_line.x = 10
center_line.y = 10
center_line = some_lane.classification.centerline.add()
center_line.x = 10
center_line.y = 20


ts = sensor_view.timestamp
ts.seconds = 10
ts.nanos = 0


#stationary = sensor_view.stationary_object.add()

print sensor_view



f = open("test_3.txt", "wb")
f.write("$$__$$")
f.write(sensor_view.SerializeToString())

f.close()

```

**Comment by kmeids** [comment]
Hei, 
I took a look into your code, I am using python 3 some I made some slight changes. 
The main problem that I can see is that you are adding the "$$__$$" at the beginning of the message, from my analysis of the src files for the osi viewer you need to concatenate it at the end of you message.

try:
```
f = open("test_3.txt", "wb")
f.write(sensor_view.SerializeToString())
f.write("$$__$$")
```

or simply:
```
f = open("test_3.txt", "wb")
f.write(sensor_view.SerializeToString() + "$$__$$") 
``` 
(not sure if you need the` b"$$__$$" `in python2)

either way here is your edited code in python 3 and below you can see the output in the visualizer (see attached image) 
Note:  Because you are adding center lanes, change the Lane type under view in the visualizer to "Center Lanes"

```
import osi_sensorview_pb2
import osi_sensordata_pb2
import osi_common_pb2

sensor_view = osi_sensorview_pb2.SensorView()
new_cam_sensor = sensor_view.camera_sensor_view.add()
ground_truth = sensor_view.global_ground_truth
some_lane =  ground_truth.lane.add()
center_line = some_lane.classification.centerline.add()
center_line.x = 0
center_line.y = 10
center_line = some_lane.classification.centerline.add()
center_line.x = 10
center_line.y = 10
center_line = some_lane.classification.centerline.add()
center_line.x = 10
center_line.y = 20


ts = sensor_view.timestamp
ts.seconds = 10
ts.nanos = 0


#stationary = sensor_view.stationary_object.add()

print (sensor_view)



f = open("test_3.pb.txt", "wb")
#f.write("$$__$$")
proto_bytes = sensor_view.SerializeToString()
f.write( proto_bytes + b'$$__$$')

f.close()

```

![image](https://user-images.githubusercontent.com/25367407/43441670-de2e859e-949b-11e8-8362-7ad70c5c8f9d.png)

**Comment by mshaheerm** [comment]
How can i use osi packaging? i have converted my simulator's result to OSI standards. now how can i use that for further use with osi packaging? and how to  visualize or interpret the results? i appreciate your help..

**Comment by jdsika** [comment]
I think the "how are the messages stored in a file" should be specified in a better way [see here](https://stackoverflow.com/questions/5586323/storing-multiple-messages-in-one-protocol-buffer-binary-file).

**Comment by jdsika** [comment]
@vkresch 
uint32 for the length of the message. Little-Endian should work for the .osi format. We wait with the compression of the messages using lzma.

**Comment by vkresch** [comment]
@jdsika why not use uint64 (unsigned long) instead if uint32 (unsigned int)? We would than have a long_range=[0, 4.294.967.295] instead of int_range= [0, 65.535].
I would prefer writing to a file like this in python (buffer is of type bytes):
`f.write(struct.pack("<L", len(buffer)) + buffer) `
where `<` stands for little endian and `L` for unsigned long.

**Comment by jdsika** [comment]
OK and Long is uint64 in this case?? I would like the code to show it specifically or is that just unclear for me?

**Comment by vkresch** [comment]
[Here](https://docs.python.org/3.6/library/struct.html#format-characters) are the defintions of python structs. See [here](https://www.tutorialspoint.com/what-is-the-difference-between-an-int-and-a-long-in-cplusplus) the difference between int and long. I think it's analog for unsigned type.

**Comment by pmai** [comment]
Not sure what the current stage of discussions is, but neither is int 32bit nor is long 64bit, since that depends on the platform (see also https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models for non-normative reference):

ILP64 (mostly extinct nowadays) means sizeof(int)==sizeof(long)==sizeof(long long)==sizeof(void*)==8 (e.g. DEC Alpha under OSF/1)
LP64 means sizeof(int)==4, sizeof(long)==sizeof(long long)==sizeof(void*)==8 (e.g. most current Linux/BSD systems)
LLP64 means sizeof(int)==sizeof(long)==4, sizeof(long long)==sizeof(void*)==8 (Win32 API on64bit, i.e. Windows)

In C nowadays it is better to directly rely on post-C90 (i.e. C99) integer types, i.e. use uint64_t instead.

While the L in the python example is long, it is specified in python to be 32bit. You would need to use Q for 8byte/64bit unsigned.

That said, currently OSI messages passed under OSMP are restricted to 32bit (actual 31bit) lengths anyway, so I would specify 32bit LE unsigned integer for size, and let implementations deal with this.

**Comment by vkresch** [comment]
@pmai thanks for the suggestion :)

**Comment by vkresch** [comment]
https://github.com/OpenSimulationInterface/open-simulation-interface/pull/358
